[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#4B9CD3"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#FFFFFF"
font = "sans serif"
